[package]
name = "rbuster"
version = "0.1.0"
authors = ["Vadim Smirnov <smirnovvad7@gmail.com>"]

[dependencies]
reqwest = "0.8"
futures = "0.2"
tokio-core = "0.1"
error-chain = "0.11"
rayon = "1.0"
quicli = "0.3"
